### ISSUE TITLE
Support for Chip version 0x04

### ISSUE THREAD

**Issue by MarcinPaszek** [fphammerle/python-cc1101#15]
Hello,
Please consider updating /home/pi/.local/lib/python3.7/site-packages/cc1101/__init__.py to support versions 0x14 aswell as 0x04. As far as I know version 0x04 has just a smaller form factor. [TI Forum Link](https://e2e.ti.com/support/wireless-connectivity/sub-1-ghz/f/156/t/428028?CC1101-version-0x14-chip-difference)

**Comment by fphammerle** [comment]
Hi,

Thanks for the report and TI forum ref!

Could you retry using the just released version `v2.4.0` ?

https://pypi.org/project/cc1101/2.4.0/

**Comment by MarcinPaszek** [comment]
Yes, I will try it out later today

**Comment by MarcinPaszek** [comment]
I've made a fresh installation on another Raspberry Pi and it seems to work fine.

**Comment by fphammerle** [comment]
Great, thanks for testing!
