### ISSUE TITLE
Sending pulses via GD00

### ISSUE THREAD

**Issue by HerbOtto** [fphammerle/python-cc1101#27]
Does your library support frequencies such as: 433.42 MHz?

for example:
```
with cc1101.CC1101() as transceiver:
		transceiver.set_base_frequency_hertz(433.42e6)
```

When I dump the registers I'm not seeing a change w/FREQ0-2

**Comment by fphammerle** [comment]
Hi,

I can confirm 433.42 MHz works cause I am controlling somfy rts shades with this library.

How did you check the registers?

```sh
$ pip3 show cc1101 | grep -i version
Version: 2.6.1
$ cc1101-export-config -f 433920000 | grep -i freq
CC1101(marcstate=idle, base_frequency=433.92MHz, symbol_rate=115.05kBaud, modulation_format=ASK_OOK, sync_mode=TRANSMIT_16_MATCH_16_BITS, preamble_length=4B, sync_word=0xd391, packet_length≤255B)
0b00010000, # 0x10 FREQ2
0b10110000, # 0xb0 FREQ1
0b01110001, # 0x71 FREQ0
$ cc1101-export-config -f 433420000 | grep -i freq
CC1101(marcstate=idle, base_frequency=433.42MHz, symbol_rate=115.05kBaud, modulation_format=ASK_OOK, sync_mode=TRANSMIT_16_MATCH_16_BITS, preamble_length=4B, sync_word=0xd391, packet_length≤255B)
0b00010000, # 0x10 FREQ2
0b10101011, # 0xab FREQ1
0b10000101, # 0x85 FREQ0
```

**Comment by fphammerle** [comment]
```python3
>>> import cc1101
>>> with cc1101.CC1101() as transceiver:
...     transceiver.set_base_frequency_hertz(433.42e6)
...     print(transceiver.get_base_frequency_hertz(), 'Hz')
...     for key, value in transceiver.get_configuration_register_values().items():
...             if 'FREQ' in key.name:
...                     print(key, value)
... 
433419952.3925781 Hz
ConfigurationRegisterAddress.FREQ2 16
ConfigurationRegisterAddress.FREQ1 171
ConfigurationRegisterAddress.FREQ0 133
```

**Comment by HerbOtto** [comment]
That's actually how I'm trying to use the radio - Somfy RTS.  I'm having issues getting it to work properly - could you provide an example of how you setup the radio?

I dumped the registers as follows... however when I tried your technique above it seem to match your values.
```
	with cc1101.CC1101() as transceiver:
		for register, value in transceiver.get_configuration_register_values().items():
			print( f"0x{register:02x}\t{register.name}\t=\t0x{value:02x}\t{value}\t0b{value:08b}" )

```

I used the following to try and stimulate GDO0...  No joy

```
with cc1101.CC1101() as transceiver:
        transceiver.set_base_frequency_hertz(433.42e6)
        with transceiver.asynchronous_transmission():
                # previously setup pigpio
                pi.wave_send_once(wid)
                while pi.wave_tx_busy(): pass

```

**Comment by fphammerle** [comment]
The cc1101 part of your code looks fine.
However, I am not familiar with the GPIO part.
Can you verify that the `GDO1` pin receives the signal?

I am using `.transmit` instead of `.asynchronous_transmission`/`GDO0` for somfy.

My configuration:
```python
transceiver.set_base_frequency_hertz(433.42e6)
transceiver.set_symbol_rate_baud(1555.56)
transceiver.set_sync_mode(cc1101.SyncMode.NO_PREAMBLE_AND_SYNC_WORD)
transceiver.set_packet_length_mode(cc1101.PacketLengthMode.FIXED)
transceiver.set_packet_length_bytes(len(payload))
transceiver.disable_checksum()
transceiver.transmit(payload)
```

I created `payload` following this guide: https://pushstack.wordpress.com/somfy-rts-protocol/

**Comment by HerbOtto** [comment]
The GPIO is used to toggle [pulse] the GDO0 pin from the Raspberry Pi - I'm using Pi-Somfy as a base library which uses pigpio in order to generate a clean pulse stream on the pi [which unlike an Arduino has indeterminate timing].  

The GDO0 pin is definitely being pulsed properly - I have an LED showing the status.  So I was using your async example as a guide.

**Comment by fphammerle** [comment]
Thanks for confirming the GDO0 signal!
Unfortunately, I currently don't have any idea why  `.asynchronous_transmission` wouldn't work then.

Does the CC1101 transmit any signal in `with transceiver.asynchronous_transmission:` or is there just silence on 433.42MHz?

**Comment by HerbOtto** [comment]
I have no way to monitor the RF output of the CC1101 which makes this increasingly difficult.

**Comment by fphammerle** [comment]
I just verified that `.asynchronous_transmission` works fine with the following script (library version `2.6.1`) :
```python
import logging, time, cc1101, RPi.GPIO
logging.basicConfig(level=logging.INFO)
RPi.GPIO.setmode(RPi.GPIO.BCM)
RPi.GPIO.setup(24, RPi.GPIO.OUT) # pin 18
with cc1101.CC1101() as transceiver:
    transceiver.set_base_frequency_hertz(433.42e6)
    with transceiver.asynchronous_transmission():
        for _ in range(4):
            for sleep_ms in range(10, 40, 10):
                RPi.GPIO.output(24, True)
                time.sleep(sleep_ms / 1000)
                RPi.GPIO.output(24, False)
                time.sleep(sleep_ms / 1000)
```

I was able to capture the signal with gnuradio companion:
![2021-01-23-121323_1982x775_scrot](https://user-images.githubusercontent.com/8507803/105576635-724a6600-5d74-11eb-8c3e-ccb2a4fd718d.png)
![2021-01-23-121030_1349x332_scrot](https://user-images.githubusercontent.com/8507803/105576637-75455680-5d74-11eb-9034-e471558cd547.png)
[cc1101_async_tx_test.grc.zip](https://github.com/fphammerle/python-cc1101/files/5860075/cc1101_async_tx_test.grc.zip)

So I suspect that signal provided by your script to GDO0 is not correct.
The asynchronous transmission mode is quite susceptible to timing issues.
Some bits might be too long or to short.

**Comment by fphammerle** [comment]
> I have no way to monitor the RF output of the CC1101 which makes this increasingly difficult.

I would suggest getting an < 20 euros RTL-SDR receiver (e.g. an RTL2832U/R820T USB dongle)
and checking the transmitted signal with gnuradio companion, [gqrx](https://gqrx.dk/) or a similar tool.

Alternatively, you could use the second CC1101 with the esp-8266 in receive mode, but SDR would probably be easier.

**Comment by HerbOtto** [comment]
I just ordered a SDR to try the exact same thing.  So what did you use for a processor to generate your Somfy packets?  I'm using a Raspberry Pi.  Any chance I can get a view of your Somfy packet generation?

**Comment by fphammerle** [comment]
> I just ordered a SDR to try the exact same thing.

Great :+1:

>  Any chance I can get a view of your Somfy packet generation?

I wrote a custom library that uses `transceiver.transmit(payload)`: https://git.hammerle.me/fphammerle/python-somfy-rts-cc1101/src/v1.2.0/somfy_rts/__init__.py#L109

The repository is private cause I am not sure whether publishing the code would infringe copyrights of somfy.

If you are interested in the code, please create a user at https://git.hammerle.me/user/sign_up
and I will grant you access afterwards

**Comment by HerbOtto** [comment]
I tried something else - I ran the above script but had it stay at a logic level [not pulse].  It appears it IS transmitting when the line is pulled LOW and not when pulled HIGH - which I find odd. I verified this with my meter.  I was able to verify it transmitting on the correct frequency since it prevented my Somfy RF remote from working while it was set low.   I was under the impression the GDO0 signal was active high - is this changeable in your driver?

**Comment by fphammerle** [comment]
you should be able to see the repository now

>  It appears it IS transmitting when the line is pulled LOW and not when pulled HIGH - which I find odd.

That's definitely a bug.
I reproduced / documented the issue using `.transmit` here: https://github.com/fphammerle/python-cc1101/issues/30

Apparently, both `.transmit` and `.asynchronous_transmit` are affected.

I would suggest we continue the discussion in #30

The library probably configures the transceiver wrongly

**Comment by tfcarlin** [comment]
> > I just ordered a SDR to try the exact same thing.
> 
> Great 👍
> 
> > Any chance I can get a view of your Somfy packet generation?
> 
> I wrote a custom library that uses `transceiver.transmit(payload)`: https://git.hammerle.me/fphammerle/python-somfy-rts-cc1101/src/v1.2.0/somfy_rts/__init__.py#L109
> 
> The repository is private cause I am not sure whether publishing the code would infringe copyrights of somfy.
> 
> If you are interested in the code, please create a user at https://git.hammerle.me/user/sign_up
> and I will grant you access afterwards

Hi, any chance I could get access to the Somfy library? Thanks! I completed the sign_up form.

**Comment by fphammerle** [comment]
Hi @tfcarlin, please see my reply to your mail

**Comment by ngutman** [comment]
hey @fphammerle I'd love to take a look on your code for using `.trasmit()` instead of `.asynchronous_transmission()` - I'm having some issues, might be related to the hardware I'm using (using E07-M1101D). Using GDO0 results in weird signal (I capture it using RTL-SDR). Thanks! (registered on your repo)
