### ISSUE TITLE
OOK-modulated signal inverted?

### ISSUE THREAD

**Issue by fphammerle** [fphammerle/python-cc1101#30]
```
$ pip3 show cc1101 | grep -i version
Version: 2.6.1
$ python3 examples/transmit_fixed_length.py
CC1101(marcstate=idle, base_frequency=433.50MHz, symbol_rate=0.60kBaud, modulation_format=ASK_OOK, sync_mode=NO_PREAMBLE_AND_SYNC_WORD, packet_length=4B)
INFO:cc1101:transmitting 0xff00aaff (b'\xff\x00\xaa\xff')
```
transmits:
![2021-01-23-142829_1335x335_scrot](https://user-images.githubusercontent.com/8507803/105579558-ada26000-5d87-11eb-95e1-6b698da45fb8.png)

[cc1101_tx_test.grc.zip](https://github.com/fphammerle/python-cc1101/files/5860260/cc1101_tx_test.grc.zip)

Signal is inverted (high-bit: signal off, low-bit: signal on)

also reported by @HerbOtto in https://github.com/fphammerle/python-cc1101/issues/27#issuecomment-766020245

**Comment by fphammerle** [comment]
@HerbOtto, could you maybe check how the asynchronous transmission behaves when the transceiver is connected to your esp-8266?

Does GDO0 also get inverted, or does it behave as expected: (GDO0 high -> signal on, GDO0 low -> signal off)?

**Comment by HerbOtto** [comment]
See page 61 of the Datasheet...

`If the IOCFGx.GDOx_CFG setting is less than 0x20 and IOCFGx_GDOx_INV is 0 (1), the GDO0 and GDO2 pins will be hardwired to 0 (1), and the GDO1 pin will be hardwired to 1 (0) in the SLEEP state. These signals will be hardwired until the CHIP_RDYn signal goes low.`

**Comment by HerbOtto** [comment]
> @HerbOtto, could you maybe check how the asynchronous transmission behaves when the transceiver is connected to your esp-8266?
> 
> Does GDO0 also get inverted, or does it behave as expected: (GDO0 high -> signal on, GDO0 low -> signal off)?

When running on the ESP-8266 using the following setup:
```
        #include <ELECHOUSE_CC1101_SRC_DRV.h>	// https://github.com/LSatan/SmartRC-CC1101-Driver-Lib
	ELECHOUSE_cc1101.Init();
	ELECHOUSE_cc1101.setMHZ(CC1101_FREQUENCY); 
	ELECHOUSE_cc1101.SetTx();

	digitalWrite(EMITTER_GPIO, LOW);   // turn OFF transmitter
	digitalWrite(EMITTER_GPIO, HIGH);  // turn ON transmitter
```

**Comment by HerbOtto** [comment]
Try this...

```
fg0 = self._read_single_byte(ConfigurationRegisterAddress.IOCFG0)
fg0 = 0b10111000
self._write_burst(
    start_register=ConfigurationRegisterAddress.IOCFG0, values=[fg0]
)        

```

**Comment by fphammerle** [comment]
Thanks a lot for checking the behavior of SmartRC-CC1101-Driver-Lib and checking the docs!

I think the problem is that I am currently **not** setting the `PATABLE` (`0x3E`) register.

After adding
```python
transceiver._write_burst(start_register=0x3E, values=[0x0, 0x34])
```
I get a signal for high-bits and no signal for low-bits.
```python
import logging
import time

import cc1101


logging.basicConfig(level=logging.INFO)

with cc1101.CC1101() as transceiver:
    transceiver.set_base_frequency_hertz(433.5e6)
    transceiver.set_symbol_rate_baud(600)
    transceiver.set_sync_mode(cc1101.SyncMode.NO_PREAMBLE_AND_SYNC_WORD)
    transceiver.set_packet_length_mode(cc1101.PacketLengthMode.FIXED)
    transceiver.set_packet_length_bytes(5)
    transceiver.disable_checksum()
    print(transceiver)
    transceiver._write_burst(start_register=0x3E, values=[0x0, 0x34])
    transceiver.transmit(b"\xff\x00\xaa\xff\x0f")
```
![2021-01-23-160445_1326x329_scrot](https://user-images.githubusercontent.com/8507803/105602287-9a968c80-5d95-11eb-9c46-228042bb99b6.png)

Could you maybe add `transceiver._write_burst(start_register=0x3E, values=[0x0, 0x??])` to your code and check if the signal then has the expected polarity?

> Bit 6 of IOCFG0

I think, `IOCFG0` settings do not influence `GDO0` interpretation / behavior in asynchronous TX (**input**) mode.

> GDO0 _INV 0 R/W Invert **output**, i.e. select active low (1) / high (0)

**Comment by HerbOtto** [comment]
I believe you meant:

`    transceiver._write_burst(start_register=0x3E, values=[0x0, 0x34]) `

Which fixed the issues I was having w/the Somfy protocol!!
Thank you!

**Comment by fphammerle** [comment]
Great!

You may want to change `0x34` to some higher number to increase the signal strength

See "24 Output Power Programming" (page 59) in docs

**Comment by fphammerle** [comment]
After upgrading to the new release `v2.7.0`, you can replace
```python
transceiver._write_burst(start_register=0x3E, values=[0x0, 0x34])
```
with
```python
transceiver.set_output_power((0, 0x34))
# or for higher output power:
transceiver.set_output_power((0, 0xC6))
```
for OOK modulation.

CC1101's default is `(0xC6, 0)` (inverted OOK).
