### ISSUE TITLE
Failed to transmit an FSK signal

### ISSUE THREAD

**Issue by Martingf56** [fphammerle/python-cc1101#35]
Hi,
I'm trying to use this library to send TPMS signals. These signals are FSK and their size is usually about 25 bytes.
Transmission is failing, i want to send this bytes _0x55555556565a95996695aa9699595556aa596556569659597e_.
I configure the library with this settings:
```    
transceiver.set_base_frequency_hertz(433.92e6) transceiver._set_modulation_format(cc1101.ModulationFormat.FSK2)
transceiver.set_symbol_rate_baud(250000)
transceiver.set_sync_mode(cc1101.SyncMode.NO_PREAMBLE_AND_SYNC_WORD)
transceiver.disable_checksum()
```
I'm using a RTL dongle to receive the signal transmitted with the CC1101. This is the signal I receive.
![image](https://user-images.githubusercontent.com/44724834/117848200-587d5200-b283-11eb-81c5-03eacbba11e3.png)
In theory the signal must be similar to this image:
![image](https://user-images.githubusercontent.com/44724834/117848604-be69d980-b283-11eb-9bb4-d57af89f43fc.png)

**Comment by fphammerle** [comment]
Hi Martin,

I just tried to reproduce your issue with the following code:
```python
import logging

import cc1101 # version 2.7.3

logging.basicConfig(level=logging.INFO)

with cc1101.CC1101(lock_spi_device=True) as transceiver:
    transceiver.set_base_frequency_hertz(433.92e6)
    transceiver._set_modulation_format(cc1101.ModulationFormat.FSK2)
    transceiver.set_symbol_rate_baud(250000)
    transceiver.set_sync_mode(cc1101.SyncMode.NO_PREAMBLE_AND_SYNC_WORD)
    transceiver.disable_checksum()
    payload = b'\x55\x55\x55\x56\x56\x5a\x95\x99\x66\x95\xaa\x96\x99\x59\x55\x56\xaa\x59\x65\x56\x56\x96\x59\x59\x7e'
    transceiver.set_packet_length_mode(cc1101.PacketLengthMode.FIXED)
    transceiver.set_packet_length_bytes(len(payload))
    print(transceiver)
    transceiver.transmit(payload)
```
output:
```
CC1101(marcstate=idle, base_frequency=433.92MHz, symbol_rate=249.94kBaud, modulation_format=FSK2, sync_mode=NO_PREAMBLE_AND_SYNC_WORD, packet_length=25B, output_power=(0xc6,0))
INFO:cc1101:transmitting 0x55555556565a95996695aa9699595556aa596556569659597e (b'UUUVVZ\x95\x99f\x95\xaa\x96\x99YUV\xaaYeVV\x96YY~')
```

I was **not** able to capture any signal with my RTL-SDR dongle.

I'll need some time to look into this.

**Comment by fphammerle** [comment]
I was able to capture the signal after adding `transceiver.set_output_power((0xC0,))`:
```python
import logging

import cc1101 # version 2.7.3

logging.basicConfig(level=logging.INFO)

with cc1101.CC1101(lock_spi_device=True) as transceiver:
    transceiver.set_base_frequency_hertz(433.92e6)
    transceiver._set_modulation_format(cc1101.ModulationFormat.FSK2)
    transceiver.set_symbol_rate_baud(600)
    transceiver.set_sync_mode(cc1101.SyncMode.NO_PREAMBLE_AND_SYNC_WORD)
    transceiver.disable_checksum()
    transceiver.set_output_power((0xC0,))
    payload = b'\x55\x55\x55\x56\x56\x5a\x95\x99\x66\x95\xaa\x96\x99\x59\x55\x56\xaa\x59\x65\x56\x56\x96\x59\x59\x7e'
    transceiver.set_packet_length_mode(cc1101.PacketLengthMode.FIXED)
    transceiver.set_packet_length_bytes(len(payload))
    print(transceiver)
    transceiver.transmit(payload)
 ```

![2021-05-12-182126_2212x864_scrot](https://user-images.githubusercontent.com/8507803/118021418-7f0ebc00-b35b-11eb-98f4-67f59aee2da7.png)
![2021-05-12-182111_1722x1548_scrot](https://user-images.githubusercontent.com/8507803/118021434-8209ac80-b35b-11eb-8027-400a015476e5.png)

[cc1101_issue_35_martingf56.grc.zip](https://github.com/fphammerle/python-cc1101/files/6468180/cc1101_issue_35_martingf56.grc.zip)

**Comment by Martingf56** [comment]
Thank you very much for answering.
I have tried your code to send the signal and I have been able to receive signals.
But I have another question. I was analyzing the signal with the Universal Radio Hacker software and it has a function in which the bits can be seen once demodulated. And these do not correspond to the payload. My question is, why when transmitting is something different than the payload transmitted?

For example:
payload -> 0x55555556565a95996695aa9699595556aa596556569659597e
In bytes -> b'UUUVVZ \ x95 \ x99f \ x95 \ xaa \ x96 \ x99YUV \ xaaYeVV \ x96YY ~ '
But the payload is the bytes that I want to transmit.

**Comment by fphammerle** [comment]
Could you provide the payload that the software records (instead of the expected `b"UUUVVZ\x95\x99f\x95\xaa\x96\x99YUV\xaaYeVV\x96YY~'"`) ?

Maybe the bit synchronization is off

**Comment by Martingf56** [comment]
What I receive doesn't make a lot of sense. I have tried to change some parameters but I can't receive a normal datagram.

![imagen](https://user-images.githubusercontent.com/44724834/118723585-e631e200-b82d-11eb-8da7-d4d77bd742ea.png)

I pass you the datagram in hexadecimal
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff000000000000000000000000000000000000000000000000

**Comment by fphammerle** [comment]
I just retried transmitting the signal with the python code posted in https://github.com/fphammerle/python-cc1101/issues/35#issuecomment-839978444

The signal that I receive with gnuradio looks ok:
![2021-05-19-123140_1220x364_scrot](https://user-images.githubusercontent.com/8507803/118798851-65f79500-b89e-11eb-9bcf-b5eb0b6d2ba4.png)
![2021-05-19-123104_1067x611_scrot](https://user-images.githubusercontent.com/8507803/118798868-698b1c00-b89e-11eb-91a2-26b2e1907c43.png)
[cc1101_issue_35_martingf56.zip](https://github.com/fphammerle/python-cc1101/files/6507943/cc1101_issue_35_martingf56.zip)
(I didn't try to decode)

Maybe the configured signal rate is too high for the transmitter or the receiver

**Comment by fphammerle** [comment]
According to the official docs, CC1101 supports sample rates from 0.6 to 500kBaud for 2-FSK, so `transceiver.set_symbol_rate_baud(250000)` should be ok

**Comment by fphammerle** [comment]
@Martingf56, please verify that your receiver is able to record signals with a signal rate of 250kBaud or try configuring a lower rate.

**Comment by Martingf56** [comment]
> @Martingf56, please verify that your receiver is able to record signals with a signal rate of 250kBaud or try configuring a lower rate.

I receive a little signal with 250kBaud, but finally i will use 5KBaud for transmit the signal.

**Comment by fphammerle** [comment]
Although you receive some signal, the sampling rate of your RTL dongle might be too low to capture the complete waveform at 250 kBaud.

Are you able to decode the 5 kBaud signal?

**Comment by Martingf56** [comment]
> Although you receive some signal, the sampling rate of your RTL dongle might be too low to capture the complete waveform at 250 kBaud.
> 
> Are you able to decode the 5 kBaud signal?

Yes, I decode the signal and the bits are equal to the payload.
Thank you so much for your help.

![Captura de pantalla de 2021-05-20 19-55-01](https://user-images.githubusercontent.com/44724834/119027670-eb666c80-b9a6-11eb-805b-e09d37ccbc43.png)

**Comment by fphammerle** [comment]
Great! :)

Please open a new issue, if you encounter another problem
