### ISSUE TITLE
Multiple CC1101

### ISSUE THREAD

**Issue by 0x5c4r3** [fphammerle/python-cc1101#42]
Is there a way to implement 2 cc1101 at the same time? So, for instance, I am able to receive with one and to transmit with the other?

Thanks

**Comment by fphammerle** [comment]
Hi,

yes, that should work.

```python
with cc1101.CC1101(spi_bus=0) as receiver, cc1101.CC1101(spi_bus=1) as transmitter:
        print(receiver, transmitter)
```

**Comment by 0x5c4r3** [comment]
perfect, I'll test it shortly. I imagine I'll need to connect the first cc1101 on the default spi0 pins and the second to the spi1 pins, but what about each GDO0 and GDO2? is there any way to declare them for each cc1101?

Thanks

**Comment by fphammerle** [comment]
`GDO2` is not require to use this library

for `.asynchronous_transmission()` and the not yet stable `_wait_for_packet`, you can connect any pin to `GDO0`.
`.trasnmit()` does not required `GDO0`.
