### ISSUE TITLE
ASK Transmission via E07-M1101D

### ISSUE THREAD

**Issue by fphammerle** [fphammerle/python-cc1101#52]
hey @fphammerle I'd love to take a look on your code for using `.trasmit()` instead of `.asynchronous_transmission()` - I'm having some issues, might be related to the hardware I'm using (using E07-M1101D). Using GDO0 results in weird signal (I capture it using RTL-SDR). Thanks! (registered on your repo) 

For reference this is the captured signal for a slightly modified version of your `.transmit()` sample - 
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/1540134/150412609-c093b97d-5a5a-430d-84ef-3b628f44bfdb.png">
```
import logging, time, cc1101
logging.basicConfig(level=logging.DEBUG)
payload1 = b"\x01\x02\x03\x04\x05\x06\x07"
payload2 = b"\x01\x01\x01\x01\x01\x01\x01"
payload3 = b"\x01\x00\x00\x00\x00\x00\x01"
with cc1101.CC1101() as transceiver:
    transceiver.set_output_power((0, 0x34))
    transceiver.set_base_frequency_hertz(433.42e6)
    transceiver.set_symbol_rate_baud(1555.56)
    transceiver.set_sync_mode(cc1101.SyncMode.NO_PREAMBLE_AND_SYNC_WORD)
    transceiver.set_packet_length_mode(cc1101.PacketLengthMode.FIXED)
    transceiver.set_packet_length_bytes(len(payload))
    transceiver.disable_checksum()
    transceiver.transmit(payload)
    time.sleep(0.1)
    transceiver.transmit(payload2)
    time.sleep(0.1)
    transceiver.transmit(payload3)
```

I do not fully understand how to submit a valid ASK Manchester code payload using it.

_Originally posted by @ngutman in https://github.com/fphammerle/python-cc1101/issues/27#issuecomment-1017868287_

**Comment by fphammerle** [comment]
Hi @ngutman,

What sampling rate did you configure on the RTL-SDR device to capture the signal above?
I suspect that the configured sampling rate was too low to capture a signal transmitted with `transceiver.set_symbol_rate_baud(1555.56)`.

I replaced `payload` with `payload1` in your code sample and received the following signal with a RTL-SDR dongle in GNU Radio Companion:
![2022-01-20-214454_2874x468_scrot](https://user-images.githubusercontent.com/8507803/150420081-c48fa997-dc5f-4b26-8620-6737d0a0d1ea.png)
![2022-01-20-214501_754x331_scrot](https://user-images.githubusercontent.com/8507803/150420088-a3377332-c135-4d52-b59d-91e23d31044b.png)

**Comment by ngutman** [comment]
I'm using 2.88Mhz sample rate, although I record to a  48Khz wav file - this might be the problem. I just installed gnuradio I'll try to use it and see if I get different results.
Still new to the RF world :)

**Comment by fphammerle** [comment]
If you like, you can reproduce my recording with the following gnuradio project file:
[cc1101_issue_27_test.grc.zip](https://github.com/fphammerle/python-cc1101/files/7908597/cc1101_issue_27_test.grc.zip) 

> btw from the screenshot I pasted I see similar signal to the one you shared

Yes, they are similar, but apparently some low bits of `payload1` got lost in your recording. Maybe that is caused by the downsampling to 48kHz.

> I’m trying to work out how to encode the Somfy payload correctly.

I have been using my cc1101 via this library to control Somfy RTS shades for >1 year now. Worked great for me so far.

I'd recommend reading these two blog posts: 
1. https://pushstack.wordpress.com/2014/04/14/reversing-somfy-rts/
2. https://pushstack.wordpress.com/somfy-rts-protocol/

CC1101 transceivers are able to manchester-encode payload directly on the hardware (see `transceiver.enable_manchester_code()`).
However, for Somfy RTS I perform the manchester encoding in software (via https://pypi.org/project/manchester-code/) as the first and final part of those signals is not manchester-encoded.

**Comment by ngutman** [comment]
Thanks I'll check it out! And looks my transceiver is working fine, this is from gnuradio (payload1)

<img width="1543" alt="image" src="https://user-images.githubusercontent.com/1540134/150427158-2b8ccf53-7976-472f-ba98-0852aeb543d0.png">

**Comment by fphammerle** [comment]
Great! Thanks for reporting back!

Please open a new issue if you experience another problem
